version: "3.8"

services:
  # api:
  #   build: ./functions
  #   container_name: server-container
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - nextapp

  client:
    build: ./src
    stdin_open: true
    container_name: client-container
    restart: always
    ports:
      - "3000:3000"
    # depends_on:
    #   - api
    networks:
      - nextapp

networks:
  nextapp:
    driver: bridge
